### ISSUE TITLE
Homework 3 Comments

### ISSUE THREAD

**Issue by rickjunli** [sttung/DAT_SF_16#3]
hey @sttung -

nice work! sounds like you know a lot about diabetes. :)

i liked how you did the list comprehension when you were plotting out the KNN accuracy as a function of K. it also helped me to see that your .fit functions took the df format directly. when i did my homework, I was not able to get the function to take df directly, so I did the following to convert into an array before putting them in the .fit function:
X_train = X_train.values
Y_train = Y_train.values

X_test = X_test.values
Y_test = Y_test.values
Your code made me go back and try taking out those four lines. It turns out that my code was not necessary! Thank you!  :+1: 

@ghego @breucopter: this homework really made us get our hands dirty with python. :+1:

**Comment by ghego** [comment]
Well structured and very readable!

Have a look at how some of your classmates handled the 0 values

Keep rocking!
